### ISSUE TITLE
气抖冷

### ISSUE THREAD

**Issue by Initial-heart-1** [LaoLittle/activate_windows#1]
看到这个项目的 Releases 我气得浑身发抖，大热天（25℃）的全身冷汗手脚冰凉，我们 x86_32 什么时候才能站起来？！

**Comment by Initial-heart-1** [comment]
这个社会还能不能好了，我们 x86_32 用户到底要怎么活着你们才满意......我不是？那没事了

**Comment by Initial-heart-1** [comment]
那，重来
眼泪不争气的流了下来，这个国家到处充斥着对 Windows arm64 用户的压迫，Windows arm64 用户何时才能真正的站起来......我又不是？那又没事了

**Comment by Initial-heart-1** [comment]
那那那，再来......
![O J (WMM3OCSUP23K{W3QT4](https://user-images.githubusercontent.com/63091661/175612804-a7271bc1-bd26-4305-ab6a-5e0d4d3f022d.png)
Cloudflare 究竟犯了什么错？！是没有买正版 Windows 吗？！为什么要飘在人家头上让激活......不是微软的提示？那那那....没事了

**Comment by Initial-heart-1** [comment]
好了不开玩笑了，问题：
1.我 x86_32 呢？
2.我 Windows arm64 呢？
3.你这浮窗怎么乱飞啊？

**Comment by LaoLittle** [comment]
1. 32位windows已上传
2. windows arm64由于winit库自身问题无法编译
3. 因为macos获取分辨率有缩放，已重新计算
